management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://studplatform-database.ctzczhzrzupg.eu-west-2.rds.amazonaws.com/mainDB
    username: postgres
    password: password256
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

logging:
  file:
    name: "log"
  config: "classpath:logback-spring.xml"